"""Public contracts and adapters for repository-scoped semantic indexing."""

from .exceptions import (
    EmbeddingAuthenticationError,
    EmbeddingDocumentError,
    EmbeddingDocumentTooLarge,
    EmbeddingInvalidRequestError,
    EmbeddingInvalidResponseError,
    EmbeddingProviderError,
    EmbeddingRateLimitError,
    EmbeddingSpaceMismatch,
    EmbeddingTransientError,
    EmbeddingVectorStoreConfigurationError,
    EmbeddingVectorStoreError,
    InvalidCodeChunkInventory,
    InvalidSearchRequest,
    RepositoryIndexNotFound,
    SemanticSearchError,
    VectorStoreConfigurationError,
    VectorStoreCorruptionError,
    VectorStoreError,
    VectorStorePublicationError,
    VectorStoreReadError,
    VectorStoreWriteError,
)
from .models import (
    EmbeddingDocument,
    EmbeddingModelIdentity,
    EmbeddingVector,
    IndexSyncResult,
    IndexSyncStatus,
    VectorRecord,
    VectorSearchResult,
)
from .providers import EmbeddingProvider, GeminiEmbeddingProvider
from .search import SemanticSearcher
from .stores import ChromaVectorStore, VectorStore
from .synchronization import SemanticIndexer

__all__ = (
    "EmbeddingDocument",
    "EmbeddingModelIdentity",
    "EmbeddingVector",
    "IndexSyncResult",
    "IndexSyncStatus",
    "VectorRecord",
    "VectorSearchResult",
    "EmbeddingVectorStoreError",
    "EmbeddingVectorStoreConfigurationError",
    "InvalidCodeChunkInventory",
    "EmbeddingDocumentError",
    "EmbeddingDocumentTooLarge",
    "EmbeddingProviderError",
    "EmbeddingAuthenticationError",
    "EmbeddingRateLimitError",
    "EmbeddingTransientError",
    "EmbeddingInvalidRequestError",
    "EmbeddingInvalidResponseError",
    "VectorStoreError",
    "VectorStoreConfigurationError",
    "VectorStoreReadError",
    "VectorStoreWriteError",
    "VectorStorePublicationError",
    "VectorStoreCorruptionError",
    "SemanticSearchError",
    "InvalidSearchRequest",
    "RepositoryIndexNotFound",
    "EmbeddingSpaceMismatch",
    "EmbeddingProvider",
    "GeminiEmbeddingProvider",
    "VectorStore",
    "ChromaVectorStore",
    "SemanticIndexer",
    "SemanticSearcher",
)
